using AutoMapper;
using Helpdesk.Data;
using Helpdesk.DTOs;
using Helpdesk.Exceptions;
using Helpdesk.Interfaces;
using Helpdesk.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using System.Security.Cryptography;
using Microsoft.Extensions.Configuration;

namespace Helpdesk.Services
{
    public class UserService : IUserService
    {
        private readonly UserManager<User> _userManager;
        private readonly RoleManager<IdentityRole<int>> _roleManager;
        private readonly IMapper _mapper;
        private readonly AppDbContext _context;
        private readonly ILogger<UserService> _logger;
        private readonly INotificationService _notificationService;
        private readonly IAuditLogService _auditLogService;
        private readonly ICurrentUserService _currentUser;
        private readonly IConfiguration _configuration;

        public UserService(
            AppDbContext context,
            UserManager<User> userManager,
            RoleManager<IdentityRole<int>> roleManager,
            IMapper mapper,
            ILogger<UserService> logger,
            INotificationService notificationService,
            IAuditLogService auditLogService,
            ICurrentUserService currentUser,
            IConfiguration configuration)
        {
            _userManager = userManager;
            _roleManager = roleManager;
            _mapper = mapper;
            _context = context;
            _logger = logger;
            _notificationService = notificationService;
            _auditLogService = auditLogService;
            _currentUser = currentUser;
            _configuration = configuration;
        }

        public async Task<IEnumerable<UserResponseDto>> GetAllUsersAsync()
        {
            try
            {
                var users = await _context.Users
                    .Where(u => u.IsActive)
                    .Include(u => u.Department)
                    .Include(u => u.UserRoles)
                        .ThenInclude(ur => ur.Role)
                    .ToListAsync();

                var result = users.Select(user =>
                {
                    var dto = _mapper.Map<UserResponseDto>(user);
                    dto.Role = user.UserRoles
                                   .Select(ur => ur.Role?.Name)
                                   .FirstOrDefault() ?? "User";
                    return dto;
                }).ToList();

                _logger.LogInformation("Retrieved {Count} active users", result.Count);
                return result;
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error retrieving all users");
                throw;
            }
        }

        public async Task<UserResponseDto> GetUserByIdAsync(int id)
        {
            try
            {
                if (id <= 0)
                    throw new ArgumentException("Invalid Id");

                var user = await _userManager.FindByIdAsync(id.ToString());

                if (user == null)
                {
                    _logger.LogWarning("User with ID {UserId} not found", id);
                    throw new NotFoundException("User", id);
                }

                var roles = await _userManager.GetRolesAsync(user);
                var result = _mapper.Map<UserResponseDto>(user);
                result.Role = roles.FirstOrDefault() ?? "User";

                _logger.LogInformation("Retrieved user with ID {UserId}", id);
                return result;
            }
            catch (NotFoundException)
            {
                throw;
            }
            catch (ArgumentException)
            {
                throw;
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error retrieving user with ID {UserId}", id);
                throw;
            }
        }

        public async Task<UserResponseDto> CreateUserAsync(CreateUserDto dto)
        {
            try
            {
                if (dto == null)
                    throw new ArgumentException("User data cannot be null");

                var existingUser = await _userManager.FindByEmailAsync(dto.Email);
                if (existingUser != null)
                {
                    _logger.LogWarning("Attempt to create user with existing email: {Email}", dto.Email);
                    throw new ValidationException("User with this email already exists");
                }

                var user = _mapper.Map<User>(dto);
                user.UserName = dto.Email;
                user.IsActive = true;
                user.DepartmentId = await ResolveDepartmentIdAsync(dto.DepartmentId, null);

                string rawPassword = dto.Password ?? GenerateRandomPassword();
                bool isAutoGenerated = string.IsNullOrEmpty(dto.Password);
                user.RequiresPasswordChange = isAutoGenerated;

                var result = await _userManager.CreateAsync(user, rawPassword);

                if (!result.Succeeded)
                {
                    var errors = string.Join(", ", result.Errors.Select(e => e.Description));
                    _logger.LogWarning("Failed to create user: {Errors}", errors);
                    throw new ValidationException(errors);
                }

                if (!await _roleManager.RoleExistsAsync(dto.Role))
                {
                    var roleCreateResult = await _roleManager.CreateAsync(new IdentityRole<int>(dto.Role));
                    if (!roleCreateResult.Succeeded)
                    {
                        var roleErrors = string.Join(", ", roleCreateResult.Errors.Select(e => e.Description));
                        _logger.LogWarning("Failed to create role {Role}: {Errors}", dto.Role, roleErrors);
                        throw new ValidationException($"Failed to create role: {roleErrors}");
                    }
                }

                await _userManager.AddToRoleAsync(user, dto.Role);

                var loginUrl = $"{_configuration["AppSettings:FrontendUrl"]}/login";
                await _notificationService.SendWelcomeEmailAsync(user, loginUrl, isAutoGenerated ? rawPassword : null);

                var dtoResult = _mapper.Map<UserResponseDto>(user);
                dtoResult.Role = dto.Role;

                await _auditLogService.LogAsync(
                    Helpdesk.Enums.AuditEventType.UserCreated,
                    Helpdesk.Enums.AuditEntityType.User,
                    user.Id,
                    $"User created: {user.Email}",
                    GetActorUserId(user.Id),
                    null,
                    new List<AuditLogDetail>
                    {
                        new AuditLogDetail { FieldName = "Email", OldValue = null, NewValue = user.Email },
                        new AuditLogDetail { FieldName = "Role", OldValue = null, NewValue = dto.Role },
                        new AuditLogDetail { FieldName = "DepartmentId", OldValue = null, NewValue = user.DepartmentId?.ToString() },
                        new AuditLogDetail { FieldName = "IsActive", OldValue = null, NewValue = user.IsActive.ToString() }
                    });

                _logger.LogInformation("User created successfully with ID: {UserId}", user.Id);
                return dtoResult;
            }
            catch (ValidationException)
            {
                throw;
            }
            catch (ArgumentException)
            {
                throw;
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error creating user");
                throw;
            }
        }

        public async Task UpdateUserAsync(UpdateUserDto dto)
        {
            if (dto == null || dto.Id <= 0)
                throw new ArgumentException("Invalid user data: ID is required.");

            var user = await _userManager.FindByIdAsync(dto.Id.ToString());

            if (user == null)
            {
                _logger.LogWarning("User with ID {UserId} not found for update", dto.Id);
                throw new NotFoundException("User", dto.Id);
            }

            var wasActive = user.IsActive;
            var oldFirstName = user.FirstName;
            var oldLastName = user.LastName;
            var oldDepartmentId = user.DepartmentId;
            var oldRole = (await _userManager.GetRolesAsync(user)).FirstOrDefault() ?? "User";

            _mapper.Map(dto, user);
            user.DepartmentId = await ResolveDepartmentIdAsync(dto.DepartmentId, user.DepartmentId);

            if (!string.IsNullOrWhiteSpace(dto.Role))
            {
                var currentRoles = await _userManager.GetRolesAsync(user);
                if (currentRoles.Any())
                    await _userManager.RemoveFromRolesAsync(user, currentRoles);

                if (!await _roleManager.RoleExistsAsync(dto.Role))
                {
                    // FIX: check role creation result instead of silently ignoring failure
                    var roleCreateResult = await _roleManager.CreateAsync(new IdentityRole<int>(dto.Role));
                    if (!roleCreateResult.Succeeded)
                    {
                        var roleErrors = string.Join(", ", roleCreateResult.Errors.Select(e => e.Description));
                        throw new ValidationException($"Failed to create role: {roleErrors}");
                    }
                }

                await _userManager.AddToRoleAsync(user, dto.Role);
            }

            var result = await _userManager.UpdateAsync(user);

            if (!result.Succeeded)
            {
                var errors = string.Join(", ", result.Errors.Select(e => e.Description));
                throw new ValidationException(errors);
            }

            await _auditLogService.LogUserChangedAsync(
                user.Id,
                $"User updated: {user.Email}",
                GetActorUserId(user.Id),
                new List<AuditLogDetail>
                {
                    new AuditLogDetail { FieldName = "FirstName", OldValue = oldFirstName, NewValue = user.FirstName },
                    new AuditLogDetail { FieldName = "LastName", OldValue = oldLastName, NewValue = user.LastName },
                    new AuditLogDetail { FieldName = "Role", OldValue = oldRole, NewValue = dto.Role },
                    new AuditLogDetail { FieldName = "DepartmentId", OldValue = oldDepartmentId?.ToString(), NewValue = user.DepartmentId?.ToString() },
                    new AuditLogDetail { FieldName = "IsActive", OldValue = wasActive.ToString(), NewValue = user.IsActive.ToString() }
                });

            if (!dto.IsActive && wasActive)
            {
                await _notificationService.SendDeactivationEmailAsync(user);
            }
        }

        public async Task DeleteUserAsync(int id)
        {
            try
            {
                if (id <= 0)
                    throw new ArgumentException("Invalid Id");

                var user = await _userManager.FindByIdAsync(id.ToString());

                if (user == null)
                {
                    _logger.LogWarning("User with ID {UserId} not found for deletion", id);
                    throw new NotFoundException("User", id);
                }

                var result = await _userManager.DeleteAsync(user);

                if (!result.Succeeded)
                {
                    var errors = string.Join(", ", result.Errors.Select(e => e.Description));
                    _logger.LogWarning("Failed to delete user {UserId}: {Errors}", id, errors);
                    throw new ValidationException(errors);
                }

                await _auditLogService.LogAsync(
                    Helpdesk.Enums.AuditEventType.UserDeleted,
                    Helpdesk.Enums.AuditEntityType.User,
                    user.Id,
                    $"User deleted: {user.Email}",
                    GetActorUserId(user.Id),
                    null,
                    new List<AuditLogDetail>
                    {
                        new AuditLogDetail { FieldName = "Email", OldValue = user.Email, NewValue = null },
                        new AuditLogDetail { FieldName = "IsDeleted", OldValue = "False", NewValue = "True" }
                    });

                _logger.LogInformation("User with ID {UserId} deleted successfully", id);
            }
            catch (NotFoundException)
            {
                throw;
            }
            catch (ValidationException)
            {
                throw;
            }
            catch (ArgumentException)
            {
                throw;
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error deleting user with ID {UserId}", id);
                throw;
            }
        }

        public async Task<int> ImportUsersFromCsvAsync(Stream csvStream)
        {
            using var reader = new StreamReader(csvStream);
            int count = 0;

            var header = await reader.ReadLineAsync();
            var rows = new List<(int LineNo, string Name, string Email, string Department, string Role)>();
            var errors = new List<string>();
            var lineNo = 1;

            while (!reader.EndOfStream)
            {
                lineNo++;
                var line = await reader.ReadLineAsync();
                if (string.IsNullOrWhiteSpace(line)) continue;

                var values = line.Split(',');
                if (values.Length < 4)
                {
                    errors.Add($"Line {lineNo}: expected Name, Email, Department, Role.");
                    continue;
                }

                rows.Add((lineNo, values[0].Trim(), values[1].Trim(), values[2].Trim(), values[3].Trim()));
            }

            foreach (var row in rows)
            {
                if (string.IsNullOrWhiteSpace(row.Name) ||
                    string.IsNullOrWhiteSpace(row.Email) ||
                    string.IsNullOrWhiteSpace(row.Department) ||
                    string.IsNullOrWhiteSpace(row.Role))
                {
                    errors.Add($"Line {row.LineNo}: all columns are required.");
                    // FIX: skip remaining checks for this row — they'd produce
                    // misleading extra errors for a row already marked invalid.
                    continue;
                }

                if (await _userManager.FindByEmailAsync(row.Email) != null)
                {
                    errors.Add($"Line {row.LineNo}: duplicate email '{row.Email}'.");
                    // FIX: same — no point checking role/dept for a duplicate row
                    continue;
                }

                if (!new[] { "Admin", "Agent", "User" }.Contains(row.Role, StringComparer.OrdinalIgnoreCase))
                    errors.Add($"Line {row.LineNo}: invalid role '{row.Role}'.");

                var departmentExists = await _context.Departments
                    .AnyAsync(d => d.Name == row.Department && d.IsActive);
                if (!departmentExists)
                    errors.Add($"Line {row.LineNo}: active department '{row.Department}' was not found.");
            }

            if (errors.Count > 0)
                throw new ValidationException(string.Join("; ", errors));

            // FIX: load all referenced departments in one query rather than
            // one FirstAsync per row in the loop below (was up to 2N DB calls).
            var referencedDeptNames = rows.Select(r => r.Department).Distinct().ToList();
            var departmentMap = await _context.Departments
                .Where(d => referencedDeptNames.Contains(d.Name) && d.IsActive)
                .ToDictionaryAsync(d => d.Name, d => d.Id);

            foreach (var row in rows)
            {
                var nameParts = row.Name.Split(' ', 2, StringSplitOptions.RemoveEmptyEntries);
                var firstName = nameParts.Length > 0 ? nameParts[0] : row.Name;
                var lastName = nameParts.Length > 1 ? nameParts[1] : string.Empty;

                var user = new User
                {
                    FirstName = firstName,
                    LastName = lastName,
                    UserName = row.Email,
                    Email = row.Email,
                    IsActive = true,
                    RequiresPasswordChange = true,
                    NotificationPreferences = new NotificationPreferences(),
                    DepartmentId = departmentMap[row.Department]
                };

                string tempPassword = GenerateRandomPassword();
                var result = await _userManager.CreateAsync(user, tempPassword);

                if (result.Succeeded)
                {
                    if (!await _roleManager.RoleExistsAsync(row.Role))
                        await _roleManager.CreateAsync(new IdentityRole<int>(row.Role));

                    await _userManager.AddToRoleAsync(user, row.Role);
                    count++;

                    var loginUrl = $"{_configuration["AppSettings:FrontendUrl"]}/login";
                    await _notificationService.SendWelcomeEmailAsync(user, loginUrl, tempPassword);
                }
            }

            return count;
        }

        public async Task UpdatePreferencesAsync(int userId, NotificationPreferencesDto dto)
        {
            var user = await _context.Users
                .Include(u => u.NotificationPreferences)
                .FirstOrDefaultAsync(u => u.Id == userId);

            if (user == null)
                throw new NotFoundException("User", userId);

            if (user.NotificationPreferences == null)
                user.NotificationPreferences = new NotificationPreferences();

            var oldPreferences = new NotificationPreferences
            {
                EmailOnTicketCreated = user.NotificationPreferences.EmailOnTicketCreated,
                EmailOnStatusChange = user.NotificationPreferences.EmailOnStatusChange,
                EmailOnComment = user.NotificationPreferences.EmailOnComment,
                EmailOnAssignment = user.NotificationPreferences.EmailOnAssignment,
                OptOutSurveys = user.NotificationPreferences.OptOutSurveys
            };

            user.NotificationPreferences.EmailOnTicketCreated = dto.EmailOnTicketCreated;
            user.NotificationPreferences.EmailOnStatusChange = dto.EmailOnStatusChange;
            user.NotificationPreferences.EmailOnComment = dto.EmailOnComment;
            user.NotificationPreferences.EmailOnAssignment = dto.EmailOnAssignment;
            user.NotificationPreferences.OptOutSurveys = dto.OptOutSurveys;

            var roles = await _userManager.GetRolesAsync(user);
            if (roles.Any(r => string.Equals(r, "Admin", StringComparison.OrdinalIgnoreCase)))
            {
                user.NotificationPreferences.EmailOnStatusChange = true;
                user.NotificationPreferences.EmailOnAssignment = true;
            }

            await _context.SaveChangesAsync();

            await _auditLogService.LogUserChangedAsync(
                user.Id,
                "User notification preferences updated.",
                GetActorUserId(user.Id),
                new List<AuditLogDetail>
                {
                    new AuditLogDetail { FieldName = "EmailOnTicketCreated", OldValue = oldPreferences.EmailOnTicketCreated.ToString(), NewValue = user.NotificationPreferences.EmailOnTicketCreated.ToString() },
                    new AuditLogDetail { FieldName = "EmailOnStatusChange", OldValue = oldPreferences.EmailOnStatusChange.ToString(), NewValue = user.NotificationPreferences.EmailOnStatusChange.ToString() },
                    new AuditLogDetail { FieldName = "EmailOnComment", OldValue = oldPreferences.EmailOnComment.ToString(), NewValue = user.NotificationPreferences.EmailOnComment.ToString() },
                    new AuditLogDetail { FieldName = "EmailOnAssignment", OldValue = oldPreferences.EmailOnAssignment.ToString(), NewValue = user.NotificationPreferences.EmailOnAssignment.ToString() },
                    new AuditLogDetail { FieldName = "OptOutSurveys", OldValue = oldPreferences.OptOutSurveys.ToString(), NewValue = user.NotificationPreferences.OptOutSurveys.ToString() }
                });
        }

        public async Task UpdateProfileAsync(int id, UpdateProfileDto dto)
        {
            var user = await _context.Users.FirstOrDefaultAsync(u => u.Id == id);
            if (user == null)
                throw new NotFoundException("User", id);

            var oldFirstName = user.FirstName;
            var oldLastName = user.LastName;
            var oldJobTitle = user.JobTitle;

            user.FirstName = dto.FirstName;
            user.LastName = dto.LastName;
            user.JobTitle = dto.JobTitle;

            await _context.SaveChangesAsync();

            await _auditLogService.LogUserChangedAsync(
                user.Id,
                "User profile updated.",
                GetActorUserId(user.Id),
                new List<AuditLogDetail>
                {
                    new AuditLogDetail { FieldName = "FirstName", OldValue = oldFirstName, NewValue = user.FirstName },
                    new AuditLogDetail { FieldName = "LastName", OldValue = oldLastName, NewValue = user.LastName },
                    new AuditLogDetail { FieldName = "JobTitle", OldValue = oldJobTitle ?? "", NewValue = user.JobTitle ?? "" }
                });
        }

        // ?? Private helpers ???????????????????????????????????????????????????????

        private async Task<int?> ResolveDepartmentIdAsync(int? requestedDepartmentId, int? existingDepartmentId)
        {
            if (requestedDepartmentId.HasValue)
            {
                var isValid = await _context.Departments
                    .AnyAsync(d => d.Id == requestedDepartmentId.Value && d.IsActive);
                if (!isValid)
                    throw new ValidationException("Department is not active or does not exist.");

                return requestedDepartmentId.Value;
            }

            if (existingDepartmentId.HasValue)
                return existingDepartmentId.Value;

            var general = await _context.Departments
                .FirstOrDefaultAsync(d => d.Name == "General" && d.IsActive);
            return general?.Id;
        }

        private int GetActorUserId(int fallbackUserId)
        {
            try
            {
                return _currentUser.UserId;
            }
            catch
            {
                return fallbackUserId;
            }
        }

        /// <summary>
        /// Generates a cryptographically random temporary password that satisfies
        /// the configured Identity password policy.
        /// FIX: replaced System.Random (predictable, clock-seeded) with
        /// RandomNumberGenerator (cryptographically secure).
        /// </summary>
        private string GenerateRandomPassword()
        {
            var options = _userManager.Options.Password;
            int length = options.RequiredLength < 8 ? 8 : options.RequiredLength;

            const string lower = "abcdefghijklmnopqrstuvwxyz";
            const string upper = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
            const string digit = "0123456789";
            const string special = "@$!%*?&";
            const string all = lower + upper + digit + special;

            var chars = new char[length];

            // Guarantee at least one of each required character class
            chars[0] = lower[RandomNumberGenerator.GetInt32(lower.Length)];
            chars[1] = upper[RandomNumberGenerator.GetInt32(upper.Length)];
            chars[2] = digit[RandomNumberGenerator.GetInt32(digit.Length)];
            chars[3] = special[RandomNumberGenerator.GetInt32(special.Length)];

            for (int i = 4; i < length; i++)
                chars[i] = all[RandomNumberGenerator.GetInt32(all.Length)];

            // Shuffle using Fisher-Yates with a secure random index
            for (int i = length - 1; i > 0; i--)
            {
                int j = RandomNumberGenerator.GetInt32(i + 1);
                (chars[i], chars[j]) = (chars[j], chars[i]);
            }

            return new string(chars);
        }
    }
}
